* Sources
http://danielweitzenfeld.github.io/passtheroc/blog/2014/10/28/bayes-premier-league/
http://stats.stackexchange.com/questions/120162/how-to-specify-a-hierarchical-bayesian-model-with-sum-to-zero-constraints


* MAGIC COMMANDS
#+BEGIN_SRC ipython :session
%matplotlib inline
%config InlineBackend.figure_format = 'retina'
#+END_SRC

#+RESULTS:
* IMPORT
#+BEGIN_SRC ipython :session
import os
import math
import warnings
warnings.filterwarnings('ignore')

from IPython.display import Image, HTML
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import pymc
#+END_SRC

#+RESULTS:
* PREPARE DATA
** READ DATA
#+BEGIN_SRC ipython :session
data_file = 'premier_league.txt'
df = pd.read_csv(data_file, sep='\t', index_col=0,)
df.head()
#+END_SRC

#+RESULTS:
#+begin_example
                ARS  AST  CAR  CHE  CRY  EVE  FUL  HUL  LIV  MCI  MUN  NEW  \
Home ╲ Away
Arsenal         NaN  1–3  2–0  0–0  2–0  1–1  2–0  2–0  2–0  1–1  0–0  3–0
Aston Villa     1–2  NaN  2–0  1–0  0–1  0–2  1–2  3–1  0–1  3–2  0–3  1–2
Cardiff City    0–3  0–0  NaN  1–2  0–3  0–0  3–1  0–4  3–6  3–2  2–2  1–2
Chelsea         6–0  2–1  4–1  NaN  2–1  1–0  2–0  2–0  2–1  2–1  3–1  3–0
Crystal Palace  0–2  1–0  2–0  1–0  NaN  0–0  1–4  1–0  3–3  0–2  0–2  0–3

                NOR  SOU  STK  SUN  SWA  TOT  WBA  WHU
Home ╲ Away
Arsenal         4–1  2–0  3–1  4–1  2–2  1–0  1–0  3–1
Aston Villa     4–1  0–0  1–4  0–0  1–1  0–2  4–3  0–2
Cardiff City    2–1  0–3  1–1  2–2  1–0  0–1  1–0  0–2
Chelsea         0–0  3–1  3–0  1–2  1–0  4–0  2–2  0–0
Crystal Palace  1–1  0–1  1–0  3–1  0–2  0–1  3–1  1–0
#+end_example

** MUNGING
*** make into a long dataframe
#+BEGIN_SRC ipython :session
df.index = df.columns
rows = []
for i in df.index:
    for c in df.columns:
        if i == c: continue
        score = df.ix[i, c]
        uscore = score.decode('utf-8') # something strange is happening eith encoding in score. I'll hack for now
        ascore = uscore.encode('ascii','replace')
        #score = [int(row) for row in score.split('-')]
        score = [int(row) for row in ascore.split('?')]
        rows.append([i, c, score[0], score[1]])
df = pd.DataFrame(rows, columns = ['home', 'away', 'home_score', 'away_score'])
df.head()
#+END_SRC

#+RESULTS:
:   home away  home_score  away_score
: 0  ARS  AST           1           3
: 1  ARS  CAR           2           0
: 2  ARS  CHE           0           0
: 3  ARS  CRY           2           0
: 4  ARS  EVE           1           1

*** create look-up table to map team names to a UIN
#+BEGIN_SRC ipython :session
teams = df.home.unique()
teams = pd.DataFrame(teams, columns=['team'])
teams['i'] = teams.index
teams.head()
#+END_SRC

#+RESULTS:
:   team  i
: 0  ARS  0
: 1  AST  1
: 2  CAR  2
: 3  CHE  3
: 4  CRY  4

*** create away and home columns
#+BEGIN_SRC ipython :session
df = pd.merge(df, teams, left_on='home', right_on='team', how='left')
df = df.rename(columns = {'i': 'i_home'}).drop('team', 1)
df = pd.merge(df, teams, left_on='away', right_on='team', how='left')
df = df.rename(columns = {'i': 'i_away'}).drop('team', 1)
df.head()
#+END_SRC

#+RESULTS:
:   home away  home_score  away_score  i_home  i_away
: 0  ARS  AST           1           3       0       1
: 1  ARS  CAR           2           0       0       2
: 2  ARS  CHE           0           0       0       3
: 3  ARS  CRY           2           0       0       4
: 4  ARS  EVE           1           1       0       5

** Extract data into arrays for pymc
#+BEGIN_SRC ipython :session
observed_home_goals = df.home_score.values
observed_away_goals = df.away_score.values
home_team = df.i_home.values
away_team = df.i_away.values
num_teams = len(df.i_home.unique())
num_games = len(home_team)
#+END_SRC

#+RESULTS:

** Initial value for strength parameters
#+BEGIN_SRC ipython :session
g = df.groupby('i_away')
att_starting_points = np.log(g.away_score.mean()) # log of mean scores when away
g = df.groupby('i_home')
def_starting_points = -np.log(g.away_score.mean())
#+END_SRC

#+RESULTS:

* MODEL
  We start assuming that we only care about total passing yards by each team.
  Further, we will ignore, for the moment, that the players on a team may change
  from one game to the next. Table below is a list of basic
  assumptions made in the current model.

| Observable                                  | $y_{gi}$             |
| Unovservable                                | $\theta_{gi}$        |
| Unit of performance                         | Expected Performance |
| Distribution of \theta_{gi}}                | ~Poisson             |
| Distribution of $y_{gi} \vert \theta_{gi} $ | ~Poisson             |

  Assume a log-linear random effect model

  \begin{equation}
  \label{eq:4}
  \begin{aligned}
  & \log{\theta_{g1}} = home + att_{h(g)} + def_{a(g)}  \\
  & \log{\theta_{g2}} = att_{a(g)} + def_{h(g)}
  \end{aligned}
  \end{equation}

  Where $home$ is the home advantage parameter. The scoring intensity, $\theta$
  is determined by the attack (offense) and defensive strengths of the teams.
  The subscripts $h$ and $a$ are for home and away, respectively. The model data
  structure consists of the game week and id, home and away teams, and total
  passing yards. An example table is presented in Table \ref{table:data-tab}.

  Note that a negative defense parameter will weaken opposing teams attacking
  parameter. We Assume

  \begin{equation}
  \begin{aligned}
  home & \sim Normal(0,0.0001)\\
  intercept & \sim Normal(0,0.001)
  \end{aligned}
  \end{equation}

#+BEGIN_SRC ipython :session
home = pymc.Normal('home', 0, .0001, value=0)
intercept = pymc.Normal('intercept', 0, .0001, value=0)
#+END_SRC

#+RESULTS:

Where $intercept$ is the average goals scored per game by the away team.
Hyper-prior (priors on hierarchical model parameter )

  \begin{equation}
  \begin{aligned}
  \mu_{att} & \sim Normal(0, .0001)\\
  \mu_{def} & \sim Normal(0, .0001)\\
  \tau_{att} & \sim Normal(0.1, 0.1)\\
  \tau_{def} & \sim Normal(0.1, 0.1)
  \end{aligned}
  \end{equation}

#+BEGIN_SRC ipython :session :file  :exports both
tau_att = pymc.Gamma('tau_att', .1, .1, value=10)
tau_def = pymc.Gamma('tau_def', .1, .1, value=10)
#+END_SRC

#+RESULTS:

To ensure identifiability, a sum-to-zero constraint on attack and defense
parameters is assumed
  \begin{equation}
  \begin{aligned}
  \sum_{t=1}^{T}att_t & = 0 \\
  \sum_{t=1}^{T}def_t & = 0 \\
  \end{aligned}
  \end{equation}

#+BEGIN_SRC ipython :session
#team-specific parameters
atts_star = pymc.Normal("atts_star",
                        mu=0,
                        tau=tau_att,
                        size=num_teams,
                        value=att_starting_points.values)
defs_star = pymc.Normal("defs_star",
                        mu=0,
                        tau=tau_def,
                        size=num_teams,
                        value=def_starting_points.values)

#+END_SRC

#+RESULTS:



#+BEGIN_SRC ipython :session

# trick to code the sum to zero contraint
@pymc.deterministic
def atts(atts_star=atts_star):
    atts = atts_star.copy()
    atts = atts - np.mean(atts_star)
    return atts

@pymc.deterministic
def defs(defs_star=defs_star):
    defs = defs_star.copy()
    defs = defs - np.mean(defs_star)
    return defs

@pymc.deterministic
def home_theta(home_team=home_team,
               away_team=away_team,
               home=home,
               atts=atts,
               defs=defs,
               intercept=intercept):
    return np.exp(intercept +
                  home +
                  atts[home_team] +
                  defs[away_team])

@pymc.deterministic
def away_theta(home_team=home_team,
               away_team=away_team,
               home=home,
               atts=atts,
               defs=defs,
               intercept=intercept):
    return np.exp(intercept +
                  atts[away_team] +
                  defs[home_team])


home_goals = pymc.Poisson('home_goals',
                          mu=home_theta,
                          value=observed_home_goals,
                          observed=True)
away_goals = pymc.Poisson('away_goals',
                          mu=away_theta,
                          value=observed_away_goals,
                          observed=True)

mcmc = pymc.MCMC([home, intercept, tau_att, tau_def,
                  home_theta, away_theta,
                  atts_star, defs_star, atts, defs,
                  home_goals, away_goals])
#+END_SRC

#+RESULTS:

#+BEGIN_SRC ipython :session
map_ = pymc.MAP( mcmc )
map_.fit()
# mcmc.sample(20000, 4000, 2)
#+END_SRC

#+RESULTS:
